### ISSUE TITLE
Milestone 1 Discussion

### ISSUE THREAD

**Issue by farrandi** [UBC-MDS/DSCI-532_2024_20_hotspot#1]
Possible Ideas:
1. Formula 1 (https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020/data)
      - Difficult to determine stakeholder and motivation
3. Strava (https://www.kaggle.com/datasets/ajitjadhav1/strava-running-activity-data?resource=download or julia's account)
      - Have not found dataset yet
5. Cards against Humanities (https://thepulseofthenation.com/#future)
      - Does not seem to have enough data
6. US universities (https://www.kaggle.com/datasets/mexwell/us-colleges-and-universities)
      - Not much information to display for dash
7. Grocery Data (https://figshare.com/articles/dataset/Area-level_grocery_purchases/7796666)
     - Not interested, we would want some map data
8. Flight prices (https://www.kaggle.com/datasets/dilwong/flightprices)
     - Interested but dataset is 31GB so....
9. Greenhouse Gas Emissions (https://github.com/owid/co2-data?tab=readme-ov-file)
     - Decided on this

Deliverables for Milestone 1:
1. `reports/m1_proposal.md` (max 1000 words): [see `milestone1.md` for more details]
     - Motivation + Purpose
     - Description of Data
     - Research Questions
     - App Sketch and Description (as `img/sketch.png`)
2. `CODE_OF_CONDUCT.md` (include a citation if you used a template from elsewhere)
3. `CONTRIBUTING.md` (include a citation if you used a template from elsewhere)
4. `src/app.py`
11. `data/raw/` (Raw data)
12. `notebooks/ ` (optional: if you start doing EDA, include your notebooks in this folder)
13. `environment.yml`

**Comment by farrandi** [comment]
Lets checkout the data from the datasets listed above and we can try ranking them based on preference.

**Comment by farrandi** [comment]
We decided on the **Greenhouse Gas Emissions** (https://github.com/owid/co2-data?tab=readme-ov-file)

**Comment by juliaeveritt** [comment]
We are going to split up the 4 components of the proposal:
Section 1: Motivation and Purpose - 
Section 2: Description of the data - 
Section 3: Research questions and usage scenarios - 
Section 4: App sketch & brief description - @monazhu

**Comment by monazhu** [comment]
Closed as milestone is completed
