### ISSUE TITLE
Add deployment URL to "About" section

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_20_hotspot#34]
@Rachel0619 @juliaeveritt @monazhu @farrandi  I'm reviewing some things regarding the apps that we need for next week. I have noticed that you have not added a deployment URL in the "About" section of your repo. Could you please add it there (see the milestone for instructions)?

**Comment by juliaeveritt** [comment]
Just added it! Thanks so much for letting us know!

**Comment by farrandi** [comment]
Closed because it is done!
