### ISSUE TITLE
Lab 4 Discussion

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/DSCI-532_2024_20_hotspot#66]
Fixes implemented
* Converted data to parquet file and added co2_per_capita and co2_per_gdp columns
* Removed Antarctica from our map to help fix scaling
* tried to remove icons from the map to further fix the width, unsuccessful, ended up changing the size of the bottom two plots instead for consistency
* added the selected year range to output text
* other layout and scaling fixes

Remaining fixes
* implement the parquet file use and see if this provides enough response speed improvement
* add the co2 per gdp plot - format will be beside the top co2 emitters plot

Other todo
* reflection
* update the gif in readme
* work on individual assignments

**Comment by monazhu** [comment]
Dashboard deployed on render.com

Completed all tasks / to-do for milestone 4!
