### ISSUE TITLE
Proposal - Create mockup for the proposed dashboard / relevant features

### ISSUE THREAD

**Issue by monazhu** [UBC-MDS/DSCI-532_2024_20_hotspot#7]
Task:
- Sketch of dashboard should be linked in the relevant proposal section
- Include a high level description of the main components of the app interface / how the user will interact with it in the proposal

**Comment by monazhu** [comment]
![image](https://github.com/UBC-MDS/DSCI-532_2024_20_hotspot/assets/7615983/7fa95933-7e74-47bd-9c24-6090850a2e6b)

I made some changes to the order of the plot so that it makes more sense (i.e., present more general data before more specific data) as well as changed some variables of interest (i.e., changed population to CO2 emission per capita as the latter makes it easier to see the relationship we want people to see). 

For the repot, we also need to include a high-level overview of the different components. I wrote up something quick, but feel free to make any changes to the blurb as you see fit!

> Our proposed dashboard comprises two parts. At the top, we provide our users with general statistics regarding the total CO2 emission for any given year, which can be adjusted by the toggle bar on the top left hand side. Based on this information, we can also see the top 10 countries in order of CO2 emission at a given point in time (as measured by cumulative CO2 emission up until that year), as well as the CO2 emission per capita for that specific year. Note that the default is set to the most recent year in which data is available (i.e., 2022). 

> At the bottom, the dashboard provides users with a way to explore the data for a given country in more detail. By default, the map shows the degree of CO2 emission by country on a colour scale, and next to it, the cumulative CO2 emission over time (orange line) as well as the change in average global temperature across the same time frame for reference (dotted blue line). Note that the latter does not change, as it serves as a meausre of global temperature change over time. By clicking on a specific country (e.g., Canada), the user will be able to see its specific cumulative CO2 emission over time. 

@farrandi @juliaeveritt @Rachel0619 please take a look at the following and let me know if there's anything you'd like for me to change by **8 PM Wednesday** (so I have time to implement changes / push my changes to the repo).

**Comment by juliaeveritt** [comment]
This looks awesome Mona!! Thanks so much

**Comment by Rachel0619** [comment]
This is amazing! Look forward to realizing this design. Thank you for the hard work!

**Comment by monazhu** [comment]
I think from an implementation perspective it would be cool. Would it make
sense to consider CO2 emissions on a non-cumulative basis (or limit the
range)? I don't know the literature well enough to say for sure but I think
typically CO2 emission is either presented as cumulative or on a yearly
basis.

**Comment by farrandi** [comment]
Fair, sounds good

**Comment by monazhu** [comment]
Okay - thanks so much for taking a look everyone! In that case I'll create a branch and push everything through :)

**Comment by monazhu** [comment]
Added section to proposal
